eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka8762.com:8762/eureka, http://eureka8761.com:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/demo?serverTimezone=UTC
    username: root
    password: root
    driver-class-name : com.mysql.jdbc.Driver

email:
    from: loonycoder@163.com
    password: GMX1016++.